### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [thohemp/6DRepNet360#3]
Thank you for sharing your great code. 😺
I have enjoyed it very much since the 6DRepNet generation. Thank you.

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/423_6DRepNet360

- My test results - Gold-YOLO (onnx) + 6DRepNet360 (50 batch / onnx)

  https://github.com/thohemp/6DRepNet360/assets/33194443/e2fa511a-68f8-4b9e-80d9-87141b6285cc

**Comment by awarebayes** [comment]
How well does it work with pointing your head backwards? Released model is for 300W-LP, which does not contain a wide range of motion, which was indicated by the paper

**Comment by PINTO0309** [comment]
I do not measure MAE because it is too cumbersome. Better than WHENet in sensory evaluation. Pitch is very weak.

https://github.com/thohemp/6DRepNet360/assets/33194443/6587bcb1-6a09-4cba-9830-af4bf0e89a24

**Comment by awarebayes** [comment]
If you are interested, I have added end to end export to onnx, with euler angles baked into onnx, tested with trt

**Comment by PINTO0309** [comment]
Thanks. 

However, I think you should open an issue on my repository or open another issue in this repository, since the content is different from the main topic of this issue. 

This issue asks, "What is the license for the model?"

**Comment by thohemp** [comment]
Hello @PINTO0309, 

thanks for your work. I add the license to the repo.
